#!/usr/bin/env bash
set -e
cd "$(dirname "$0")/.."
# shellcheck disable=SC1091
source "s/_tools.sh"

echo_info "Checking requirements..."
s/check_requirements

echo_info "Installing dependencies..."
npm install

echo version="$(git rev-parse --short HEAD)" | jo > build-version.json

echo_info "Linting..."
npm exec -- eslint src/*.ts src/*.tsx

echo_info "Cleaning build"
rm -rf prod/dist/

echo_info "Building..."
npm exec -- vite build --config=./vite.prod.config.js

echo_info "Linking..."
ln -s ./chat.html prod/dist/index.html
