#!/usr/bin/env bash
set -e
cd "$(dirname "$0")/.."
# shellcheck disable=SC1091
source "s/_tools.sh"

echo_info "Checking requirements..."
s/check_requirements

echo_info "Installing dependencies..."
npm install

find src -type f -name '*.test.*' | while read -r TEST_SRC; do
    jo src="/$TEST_SRC"
done | jo -a > test-manifest.json

find src -type f -name '*.examples.html' | while read -r TEST_SRC; do
    jo src="/$TEST_SRC"
done | jo -a > examples-manifest.json

echo_info "Running dev server..."
npm exec -- vite --open
